import { type ConversationMessage, type ConversationSession, type FileDocument, type ProjectInfo, type TreeNode, type TreeNodeKind, type WikiDocument, type WikiEntry, type WikiType } from '../../src/shared/types.js';
export declare function ensureProjectStructure(rootPath: string): Promise<ProjectInfo>;
export declare function listProjectTree(rootPath: string): Promise<TreeNode>;
export declare function readChapter(chapterPath: string): Promise<FileDocument>;
export declare function writeChapter(chapterPath: string, content: string): Promise<FileDocument>;
export declare function createChapter(rootPath: string, title: string): Promise<FileDocument>;
export declare function readWikiEntry(entryPath: string): Promise<WikiDocument>;
export declare function createWikiEntry(rootPath: string, type: WikiType, name: string, description?: string): Promise<WikiDocument>;
export declare function updateWikiEntry(entryPath: string, entry: WikiEntry): Promise<WikiDocument>;
export declare function listWikiDocuments(rootPath: string): Promise<WikiDocument[]>;
export declare function createConversation(rootPath: string, title: string): Promise<ConversationSession>;
export declare function readConversation(conversationPath: string): Promise<ConversationSession>;
export declare function appendConversationMessage(conversationPath: string, message: ConversationMessage): Promise<ConversationSession>;
export declare function removeLastAssistantMessage(conversationPath: string): Promise<ConversationSession>;
export declare function renameNode(targetPath: string, kind: TreeNodeKind, nextName: string): Promise<string>;
export declare function deleteNode(targetPath: string): Promise<void>;
export declare function resolveWikiPath(rootPath: string, entry: WikiEntry): string;
